-- Add all potential missing columns for members table
ALTER TABLE public.members 
ADD COLUMN IF NOT EXISTS photo text,
ADD COLUMN IF NOT EXISTS dob date,
ADD COLUMN IF NOT EXISTS place_of_birth text,
ADD COLUMN IF NOT EXISTS mother_tongue text,
ADD COLUMN IF NOT EXISTS salvation_date date,
ADD COLUMN IF NOT EXISTS salvation_place text,
ADD COLUMN IF NOT EXISTS previous_church text,
ADD COLUMN IF NOT EXISTS reason_for_coming text,
ADD COLUMN IF NOT EXISTS faith text,
ADD COLUMN IF NOT EXISTS field_of_study text,
ADD COLUMN IF NOT EXISTS educational_level text,
ADD COLUMN IF NOT EXISTS employment_status text,
ADD COLUMN IF NOT EXISTS workplace_address text,
ADD COLUMN IF NOT EXISTS income_amount numeric,
ADD COLUMN IF NOT EXISTS marital_status text,
ADD COLUMN IF NOT EXISTS spouse_name text,
ADD COLUMN IF NOT EXISTS marriage_date date,
ADD COLUMN IF NOT EXISTS marriage_place text,
ADD COLUMN IF NOT EXISTS children jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS additional_family_info text,
ADD COLUMN IF NOT EXISTS living_situation text,
ADD COLUMN IF NOT EXISTS service_type text,
ADD COLUMN IF NOT EXISTS service_duration text,
ADD COLUMN IF NOT EXISTS service_responsibility text,
ADD COLUMN IF NOT EXISTS current_service text,
ADD COLUMN IF NOT EXISTS spiritual_gift text,
ADD COLUMN IF NOT EXISTS future_service text,
ADD COLUMN IF NOT EXISTS additional_service_info text,
ADD COLUMN IF NOT EXISTS fellowship_start_date date,
ADD COLUMN IF NOT EXISTS fellowship_name text,
ADD COLUMN IF NOT EXISTS fellowship_responsibility text,
ADD COLUMN IF NOT EXISTS fellowship_mentor text,
ADD COLUMN IF NOT EXISTS fellowship_leader text,
ADD COLUMN IF NOT EXISTS additional_fellowship_info text,
ADD COLUMN IF NOT EXISTS member_signature text,
ADD COLUMN IF NOT EXISTS form_filled_date date,
ADD COLUMN IF NOT EXISTS fellowship_leader_signature text,
ADD COLUMN IF NOT EXISTS zone_rep_signature text,
ADD COLUMN IF NOT EXISTS middle_sector_rep_signature text,
ADD COLUMN IF NOT EXISTS status text DEFAULT 'Active';

-- Ensure RLS policies allow reading/writing these columns (usually covered by existing table policies)
-- But we might want to ensure the table is enabled for RLS
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
